<?php
// Auto-generated by installer — do not edit manually
return [
    'db_host'       => 'localhost',
    'db_name'       => '',
    'db_user'       => '',
    'db_pass'       => '',
    'app_url'       => '',
    'app_name'      => 'BT-Support',
    'app_lang'      => 'es',
    'timezone'      => 'America/Costa_Rica',
    'installed'     => false,
    'smtp_host'     => '',
    'smtp_port'     => 587,
    'smtp_user'     => '',
    'smtp_pass'     => '',
    'smtp_from'     => '',
    'smtp_from_name'=> 'BT-Support',
    'smtp_secure'   => 'tls',
    'mail_method'   => 'php',
    'upload_max_mb' => 10,
    'session_timeout'=> 120,
];
